// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "SiliconFlow Lab",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "SiliconFlow Lab",
            targets: ["AppModule"],
            bundleIdentifier: "com.prak59459.SiliconFlowLab",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .sparkle),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                "SiliconFlowKit"
            ],
            path: "Sources/AppModule"
        ),
        .target(
            name: "SiliconFlowKit",
            path: "Sources/SiliconFlowKit"
        )
    ]
)
